apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: circuitbreakerrules.datasource.sentinel.io
  namespace: default
  labels:
    sentinel-datasource: k8s
spec:
  group: datasource.sentinel.io
  names:
    kind: CircuitBreakerRules
    listKind: CircuitBreakerRulesList
    plural: circuitbreakerrules
    singular: circuitbreakerrule
    shortNames:
    - cbrs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: CircuitBreakerRules is the Schema for the circuit breaker rules API
      properties:
        apiVersion:
          description: 'Kind is a string value representing the REST resource this object represents.'
          type: string
        kind:
          description: 'APIVersion defines the versioned schema of this representation of an object.'
          type: string
        metadata:
          type: object
        spec:
          description: CircuitBreakerRulesSpec defines the desired state of CircuitBreakerRules
          properties:
            rules:
              description: 'rules is the circuit breaker rule list'
              items:
                properties:
                  resource:
                    type: string
                    minLength: 1
                    maxLength: 100
                  strategy:
                    type: string
                    enum:
                    - SlowRequestRatio
                    - ErrorRatio
                    - ErrorCount
                  retryTimeoutMs:
                    format: int32
                    type: integer
                    default: 1000
                    minimum: 1
                  minRequestAmount:
                    format: int64
                    type: integer
                    default: 10
                    minimum: 1
                  statIntervalMs:
                    format: int32
                    type: integer
                    default: 10000
                    minimum: 1
                  maxAllowedRtMs:
                    format: int64
                    type: integer
                    minimum: 1
                  maxSlowRequestRatio:
                    type: number
                    format: float
                  errorCountThreshold:
                    format: int64
                    type: integer
                    minimum: 1
                  errorRatioThreshold:
                    type: number
                    format: float
                required:
                - resource
                - strategy
                type: object
              type: array
          required:
          - rules
          type: object
        status:
          description: CircuitBreakerRulesStatus defines the observed state of CircuitBreakerRules
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
