apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hotspotrules.datasource.sentinel.com
  namespace: default
  labels:
    sentinel-datasource: k8s
spec:
  group: datasource.sentinel.com
  names:
    kind: HotspotRules
    listKind: HotspotRulesList
    plural: hotspotrules
    singular: hotspotrule
    shortNames:
    - hrs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: HotspotRules is the Schema for the hotspotrules API
      properties:
        apiVersion:
          description: 'Kind is a string value representing the REST resource this object represents.'
          type: string
        kind:
          description: 'APIVersion defines the versioned schema of this representation of an object.'
          type: string
        metadata:
          type: object
        spec:
          description: HotspotRulesSpec defines the desired state of HotspotRules
          properties:
            rules:
              description: 'rules is the hot spot(frequency) rule list'
              items:
                properties:
                  resource:
                    type: string
                    minLength: 1
                    maxLength: 100
                  metricType:
                    type: integer
                    format: int32
                    enum:
                    - 0
                    - 1
                  controlBehavior:
                    type: integer
                    format: int32
                    enum:
                    - 0
                    - 1
                  paramIndex:
                    description: ParamIndex is the index in context arguments list.
                    type: integer
                    minimum: 0
                  threshold:
                    format: number
                    type: float
                  maxQueueingTimeMs:
                    description: MaxQueueingTimeMs is the max queueing time in Throttling ControlBehavior
                    format: int64
                    type: integer
                    minimum: 0
                  burstCount:
                    format: int64
                    type: integer
                    minimum: 0
                  durationInSec:
                    format: int64
                    type: integer
                    minimum: 0
                  paramsMaxCapacity:
                    format: int64
                    type: integer
                    minimum: 1
                  specificItems:
                    description: specific item list
                    items:
                      description: 'specific item'
                      properties:
                        valKind:
                          format: int32
                          type: integer
                          enum:
                          - 0
                          - 1
                          - 2
                          - 3
                        valStr:
                          type: string
                          minLength: 1
                          maxLength: 100
                        specificThreshold:
                          format: int64
                          type: integer
                          minimum: 0
                      required:
                      - valKind
                      - valStr
                      - specificThreshold
                      type: object
                    type: array
                required:
                - resource
                - metricType
                - controlBehavior
                - paramIndex
                - threshold
                - maxQueueingTimeMs
                - burstCount
                - durationInSec
                - paramsMaxCapacity
                - specificItems
                type: object
              type: array
          required:
          - rules
          type: object
        status:
          description: HotspotRulesStatus defines the observed state of HotspotRules
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
